name: Push actions
run-name: ${{ github.actor }} is using GitHub Actions ğŸš€
on: [push]
jobs:
  TerraformTests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: terraform-fmt
        uses: dflook/terraform-fmt@v1.29.1
      - run: echo "ğŸ This job's status is ${{ job.status }}."
